name: 'C++ Performance Profiler'
description: 'Profiles C/C++ binaries for memory leaks and CPU hotspots using Valgrind & gperftools'
branding:
  icon: activity
  color: purple

inputs:
  binaries:
    description: 'Space-separated list of executable files to profile (relative to repo root)'
    required: true
  
  valgrind-memcheck:
    description: 'Run Valgrind memcheck (memory leaks)'
    default: 'true'
  
  valgrind-callgrind:
    description: 'Run Valgrind callgrind (CPU profiling)'
    default: 'false'

  valgrind-cachegrind:
    description: 'Run Valgrind Cachegrind (pure L1/LL cache simulation)'
    required: false
    default: 'false'
  
  valgrind-cachegrind-out-file:
    description: 'Cachegrind output filename pattern (%p = PID)'
    required: false
    default: 'cachegrind.out.%p'    
  
  gperftools:
    description: 'Run gperftools (CPU profiling – binary must be linked with -lprofiler)'
    default: 'false'

  fail-on-leak:
    description: 'Fail the job if a memory leak is detected'
    default: 'true'

  apt-packages:
    description: 'Space-separated list of apt packages to install at runtime'
    required: false
    default: ''

  ld-library-path:
    description: 'Colon-separated list of directories for custom .so files'
    required: false
    default: ''    

  run-args:
    description: 'Space-separated runtime arguments to pass to each binary'
    required: false
    default: ''

outputs:
  artifacts:
    description: 'Path to uploaded profiling artifacts'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/boxtob/cpp-perf-action:1.1.4'
  args:
      - ${{ inputs.binaries }}
  env:
    INPUT_BINARIES: ${{ inputs.binaries }}
    INPUT_VALGRIND_MEMCHECK: ${{ inputs.valgrind-memcheck }}
    INPUT_VALGRIND_CALLGRIND: ${{ inputs.valgrind-callgrind }}
    INPUT_VALGRIND_CACHEGRIND: ${{ inputs.valgrind-cachegrind }}
    INPUT_VALGRIND_CACHEGRIND_OUT_FILE: ${{ inputs.valgrind-cachegrind-out-file }}
    INPUT_GPERFTOOLS: ${{ inputs.gperftools }}
    INPUT_FAIL_ON_LEAK: ${{ inputs.fail-on-leak }} 
    INPUT_APT_PACKAGES: ${{ inputs.apt-packages }}
    INPUT_LD_LIBRARY_PATH: ${{ inputs.ld-library-path }}    
    INPUT_RUN_ARGS: ${{ inputs.run-args }}